# Generated by Django 5.1.6 on 2025-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='date_found',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date_lost',
            field=models.CharField(max_length=255),
        ),
    ]
