# Generated by Django 5.1.6 on 2025-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_lostitem_is_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
